export const predefinedItems = [
    {
      COD_ITEM: 'BCF-RR02',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '500',
      PRC_VTA_UNIT_ITEM: '590',
      VAL_VTA_ITEM: '500',
      MNT_BRUTO: '500.00',
      MNT_PV_ITEM: '590',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '90',
      TXT_DESC_ITEM: 'PRODUCTO 2',
    },
    {
      COD_ITEM: 'ABC-RR03',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '350',
      PRC_VTA_UNIT_ITEM: '350',
      VAL_VTA_ITEM: '350',
      MNT_BRUTO: '350.00',
      MNT_PV_ITEM: '413.00',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '63.00',
      TXT_DESC_ITEM: 'PRODUCTO 3'
    },    
    {
      COD_ITEM: 'DEF-RR04',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '450',
      PRC_VTA_UNIT_ITEM: '530',
      VAL_VTA_ITEM: '450',
      MNT_BRUTO: '450.00',
      MNT_PV_ITEM: '530',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '81',
      TXT_DESC_ITEM: 'PRODUCTO 4',
    },
    {
      COD_ITEM: 'GHI-RR05',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '200',
      PRC_VTA_UNIT_ITEM: '250',
      VAL_VTA_ITEM: '200',
      MNT_BRUTO: '200.00',
      MNT_PV_ITEM: '250',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '36',
      TXT_DESC_ITEM: 'PRODUCTO 5',
    },
    {
      COD_ITEM: 'JKL-RR06',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '700',
      PRC_VTA_UNIT_ITEM: '800',
      VAL_VTA_ITEM: '700',
      MNT_BRUTO: '700.00',
      MNT_PV_ITEM: '800',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '126',
      TXT_DESC_ITEM: 'PRODUCTO 6',
    },
    {
      COD_ITEM: 'MNO-RR07',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '350',
      PRC_VTA_UNIT_ITEM: '400',
      VAL_VTA_ITEM: '350',
      MNT_BRUTO: '350.00',
      MNT_PV_ITEM: '400',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '63',
      TXT_DESC_ITEM: 'PRODUCTO 7',
    },
    {
      COD_ITEM: 'PQR-RR08',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '600',
      PRC_VTA_UNIT_ITEM: '720',
      VAL_VTA_ITEM: '600',
      MNT_BRUTO: '600.00',
      MNT_PV_ITEM: '720',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '108',
      TXT_DESC_ITEM: 'PRODUCTO 8',
    },
    {
      COD_ITEM: 'STU-RR09',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '100',
      PRC_VTA_UNIT_ITEM: '120',
      VAL_VTA_ITEM: '100',
      MNT_BRUTO: '100.00',
      MNT_PV_ITEM: '120',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '18',
      TXT_DESC_ITEM: 'PRODUCTO 9',
    },
    {
      COD_ITEM: 'VWX-RR10',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '800',
      PRC_VTA_UNIT_ITEM: '900',
      VAL_VTA_ITEM: '800',
      MNT_BRUTO: '800.00',
      MNT_PV_ITEM: '900',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '144',
      TXT_DESC_ITEM: 'PRODUCTO 10',
    },
    {
      COD_ITEM: 'YZA-RR11',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '900',
      PRC_VTA_UNIT_ITEM: '1100',
      VAL_VTA_ITEM: '900',
      MNT_BRUTO: '900.00',
      MNT_PV_ITEM: '1100',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '162',
      TXT_DESC_ITEM: 'PRODUCTO 11',
    },
    {
      COD_ITEM: 'BCD-RR12',
      COD_UNID_ITEM: 'NIU',
      VAL_UNIT_ITEM: '1500',
      PRC_VTA_UNIT_ITEM: '1800',
      VAL_VTA_ITEM: '1500',
      MNT_BRUTO: '1500.00',
      MNT_PV_ITEM: '1800',
      COD_TIP_PRC_VTA: '01',
      COD_TIP_AFECT_IGV_ITEM: '10',
      COD_TRIB_IGV_ITEM: '1000',
      POR_IGV_ITEM: '18',
      MNT_IGV_ITEM: '270',
      TXT_DESC_ITEM: 'PRODUCTO 12',
    },
  ];